# **NUMPY BASICS**



In [0]:
import numpy as np #importing the third party library "Numpy" a.k.a Numerical python  

***Create an array***

In [34]:
array1d = np.array([1,2,3]) 
print(array1d)
print(type(array1d))
#we can also use string instead of integers
array1d = np.array(["a","b","c"]) 
print(array1d)
print(type(array1d))

[1 2 3]
<class 'numpy.ndarray'>
['a' 'b' 'c']


numpy.ndarray

***Range of array***

In [4]:
array_arange1 = np.arange(1,10,1) 
array_arange2 = np.arange(1,10,2)
array_arange3 = np.arange(1,10,3)

print(array_arange1)
print(array_arange2)
print(array_arange3)  

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[1 4 7]


***Generate random array***

In [13]:
array_random1 = np.random.randint(0,10,2)
array_random2 = np.random.randint(0,10,5)
array_random3 = np.random.randint(0,10,10)
print(array_random1)
print(array_random2)
print(array_random3)

[3 6]
[9 3 1 4 7]
[0 2 7 1 1 6 4 2 3 5]


***Zeros & Ones***

In [22]:
#Zeros
zero1 = np.zeros(5)
print(zero1)
zero2 = np.zeros([3,3])
print(zero2)
zero3 = np.zeros([2,2],int)
print(zero3)
print("----------------------------------------------------")
print("----------------------------------------------------")
#Ones
one1 = np.ones(5)
print(one1)
one2 = np.ones([3,3])
print(one2)
one3 = np.ones([2,2],int)
print(one3)
type(one3)



[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0]
 [0 0]]
----------------------------------------------------
----------------------------------------------------
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1]
 [1 1]]


numpy.ndarray

***To find Maximum, minimum, mean***

In [29]:
array_arange1 = np.arange(1,10,2) 
print(array_arange1)
array_arange1.max()
print("The max: ",array_arange1.max())
print("The min: ",array_arange1.min())
print("The mean: ",array_arange1.mean())
print("The sum: ",array_arange1.sum())

[1 3 5 7 9]
The max:  9
The min:  1
The mean:  5.0
The sum:  25


***Slice***

In [7]:
print(array_arange1)
print(array_arange1[0])
print(array_arange1[1])
print(array_arange1[2])
print(array_arange1[3])
print(array_arange1[0:4])
print(array_arange1[:4])
print(array_arange1[:])

[1 2 3 4 5 6 7 8 9]
1
2
3
4
[1 2 3 4]
[1 2 3 4]
[1 2 3 4 5 6 7 8 9]
